artgris_maintenance:
  #enable: false                 # Enable|Disable maintenance - default: false
  enable: '%env(bool:APP_MAINTENANCE_MODE)%'
  ips: ["127.0.0.1","::1",...] # IPs allow (prod) - default: []
  response: 503                # Maintenance Page HTTP Status Code - default: 503