artgris_maintenance:
  enable: true                 # Enable|Disable maintenance - default: false
  ips: ["127.0.0.1","::1",...] # IPs allow (prod) - default: []
  response: 503                # Maintenance Page HTTP Status Code - default: 503