name: CD/CI

on:
  push:

jobs:
  commit-stage-workflow:
    name: Commit Stage
    uses: zerai/avsym/.github/workflows/commit-stage.yaml@main
    secrets: inherit
    with:
      triggering-sha: "${{ github.sha }}"

#  acceptance-stage-workflow:
#    name: Acceptance Stage
#    needs:
#      - commit-stage-workflow
#    uses: zerai/avsym/.github/workflows/acceptance-stage.yaml@main
#    with:
#      triggering-sha: "${{ github.sha }}"
#
  publish-metrics-workflow:
    name: Publish Metrics
    needs:
      - commit-stage-workflow
      #- acceptance-stage-workflow
    uses: zerai/avsym/.github/workflows/publish-coverage-metrics.yaml@main
    with:
      triggering-sha: "${{ github.sha }}"

  deploy-on-staging-workflow:
    name: Deploy on Staging environment
    needs:
      - commit-stage-workflow
      #- acceptance-stage-workflow
    uses: zerai/avsym/.github/workflows/deploy-stage.yaml@main
    secrets: inherit
    with:
      triggering-sha: "${{ github.sha }}"
